[workspace]
members = ["launcher", "yanagi"]
resolver = "2"

[workspace.package]
version = "0.0.1"

[workspace.dependencies]
windows = "0.58.0"
ilhook = "2.1.1"
thiserror = "1.0.64"
num_enum = "0.7.3"
