[package]
name = "trigger-database"
edition = "2024"
version.workspace = true

[dependencies]
sea-orm.workspace = true
serde.workspace = true
tracing.workspace = true

entity = { path = "entity" }
migration = { path = "migration" }
