[package]
name = "blockfile"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder.workspace = true
hex.workspace = true

aes = "0.8.4"
ecb = { version = "0.1.2", features = ["alloc"] }
lz4_flex = "0.11.3"
