[package]
name = "net-msg"
version = "0.1.0"
edition = "2021"

[dependencies]
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
prost-build.workspace = true
serde_json.workspace = true
