server_name = "nap_dev_01"
bind_client_version = "OSPRODWin1.3.0"
design_data_url = "http://127.0.0.1:10000/design_data/NAP_Publish_AppStore_1.4"

[database]
url = "localhost:8000"
username = "root"
password = "root"
