[package]
name = "proto"
edition = "2021"
version.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
proto-derive.workspace = true

[build-dependencies]
prost-build.workspace = true
