[package]
name = "qwer-client-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
common.workspace = true
tracing.workspace = true

protocol.workspace = true
qwer.workspace = true
qwer-rpc.workspace = true
