[package]
name = "trigger-cryptography"
edition = "2024"
version.workspace = true

[dependencies]
rsa.workspace = true
rand.workspace = true
rand_mt.workspace = true
thiserror.workspace = true
byteorder.workspace = true
