[network]
http_addr = "127.0.0.1:10100"

[[region]]
name = "trigger_rs"
title = "Trigger-RS"
ping_url = "http://127.0.0.1:10100/ping"
dispatch_url = "http://127.0.0.1:10100/query_gateway"
biz = "nap_global"
env = 2
area = 2

[bound_server]
name = "trigger_rs"
title = "Trigger-RS"
seed = "95dedfc7cf06cdc2"
addr = "127.0.0.1"
port = 20501
is_kcp = false

